-- SQLite
CREATE TABLE IF NOT EXISTS users ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    uid TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    club_role TEXT NOT NULL
); 
